apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-tracker-backend
  labels:
    app: flight-tracker-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-tracker-backend
  template:
    metadata:
      labels:
        app: flight-tracker-backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/flight-tracker-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flight-tracker-backend
spec:
  selector:
    app: flight-tracker-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
