apiVersion: v1
kind: Service
metadata:
  name: flight-tracker-backend
  namespace: flight-tracker-namespace # Use the same namespace as your backend Deployment
spec:
  selector:
    app: flight-tracker-backend # This label should match the Deployment's labels
  ports:
    - protocol: TCP
      port: 80         # External port for communication
      targetPort: 5000 # The container port defined in the Deployment
  type: ClusterIP       # Use "LoadBalancer" for external access, or "NodePort"
